name: Bump Homebrew formula

on:
  release:
    types: [published]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: chyron
          homebrew-tap: mrlemoos/homebrew-chyron
          base-branch: main
          download-url: https://github.com/mrlemoos/chyron/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
